import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { ClipboardList, Plus, Calendar, AlertTriangle, CheckCircle, Clock } from "lucide-react";
import { format, isPast, isToday } from "date-fns";

const CycleCounts = () => {
  const navigate = useNavigate();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [statusFilter, setStatusFilter] = useState("active");
  const [showCreateDialog, setShowCreateDialog] = useState(false);

  const [newCount, setNewCount] = useState({
    scheduledDate: format(new Date(), 'yyyy-MM-dd'),
    countType: 'scheduled',
    categoryFilter: '',
    includeOpenContainers: true
  });

  const { data: counts, isLoading } = useQuery({
    queryKey: ['cycle-counts', statusFilter],
    queryFn: async () => {
      let query = supabase
        .from('cycle_counts')
        .select(`
          *,
          assigned_to_user:profiles!assigned_to(full_name),
          reviewed_by_user:profiles!reviewed_by(full_name)
        `)
        .order('scheduled_date', { ascending: true });

      if (statusFilter === 'active') {
        query = query.in('status', ['scheduled', 'in_progress', 'pending_review']);
      } else if (statusFilter !== 'all') {
        query = query.eq('status', statusFilter);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data;
    }
  });

  const createMutation = useMutation({
    mutationFn: async () => {
      const userId = (await supabase.auth.getUser()).data.user?.id;

      // Get inventory items to count based on filters
      let inventoryQuery = supabase
        .from('receiving_lots')
        .select(`
          id, material_id, quantity_received, unit_id, current_location_id,
          material:materials(id, name, category)
        `)
        .gt('quantity_received', 0)
        .eq('hold_status', 'none');

      const { data: inventory } = await inventoryQuery;

      // Filter by category if specified
      let filteredInventory = inventory || [];
      if (newCount.categoryFilter) {
        filteredInventory = filteredInventory.filter(
          (inv: any) => inv.material?.category === newCount.categoryFilter
        );
      }

      // Create count header - count_number is auto-generated by trigger
      const { data: count, error: countError } = await supabase
        .from('cycle_counts')
        .insert([{
          count_number: `CC-${new Date().getFullYear()}-${Date.now()}`, // Placeholder, trigger will override
          scheduled_date: newCount.scheduledDate,
          count_type: newCount.countType,
          category_filter: newCount.categoryFilter || null,
          include_open_containers: newCount.includeOpenContainers,
          total_items: filteredInventory.length,
          created_by: userId
        }])
        .select()
        .single();

      if (countError) throw countError;

      // Create count items
      if (filteredInventory.length > 0) {
        const items = filteredInventory.map((inv: any) => ({
          cycle_count_id: count.id,
          receiving_lot_id: inv.id,
          material_id: inv.material_id,
          location_id: inv.current_location_id || inv.location_id,
          system_quantity: inv.quantity_received,
          system_unit_id: inv.unit_id
        })).filter((item: any) => item.location_id);

        if (items.length > 0) {
          const { error: itemsError } = await supabase
            .from('cycle_count_items')
            .insert(items);

          if (itemsError) throw itemsError;
        }
      }

      return count;
    },
    onSuccess: (count) => {
      toast({
        title: "Cycle Count Created",
        description: `${count.count_number} has been scheduled.`
      });
      setShowCreateDialog(false);
      queryClient.invalidateQueries({ queryKey: ['cycle-counts'] });
    },
    onError: (error: any) => {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive"
      });
    }
  });

  const getStatusBadge = (count: any) => {
    if (count.status === 'approved') {
      return <Badge variant="default" className="bg-green-500">Approved</Badge>;
    }
    if (count.status === 'pending_review') {
      return <Badge variant="secondary" className="bg-yellow-500 text-white">Review</Badge>;
    }
    if (count.status === 'in_progress') {
      return <Badge variant="secondary" className="bg-blue-500 text-white">In Progress</Badge>;
    }
    if (isPast(new Date(count.scheduled_date)) && count.status === 'scheduled') {
      return <Badge variant="destructive">Overdue</Badge>;
    }
    if (isToday(new Date(count.scheduled_date))) {
      return <Badge variant="outline" className="border-orange-500 text-orange-600">Due Today</Badge>;
    }
    return <Badge variant="outline">Scheduled</Badge>;
  };

  return (
    <div className="space-y-6 p-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <ClipboardList className="h-8 w-8 text-primary" />
          <h1 className="text-3xl font-bold">Cycle Counts</h1>
        </div>
        <Dialog open={showCreateDialog} onOpenChange={setShowCreateDialog}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="h-4 w-4 mr-2" />
              New Count
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Schedule Cycle Count</DialogTitle>
            </DialogHeader>
            <div className="space-y-4">
              <div>
                <Label>Scheduled Date</Label>
                <Input
                  type="date"
                  value={newCount.scheduledDate}
                  onChange={(e) => setNewCount({ ...newCount, scheduledDate: e.target.value })}
                />
              </div>
              <div>
                <Label>Count Type</Label>
                <Select
                  value={newCount.countType}
                  onValueChange={(v) => setNewCount({ ...newCount, countType: v })}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="scheduled">Scheduled</SelectItem>
                    <SelectItem value="spot">Spot Check</SelectItem>
                    <SelectItem value="full_physical">Full Physical</SelectItem>
                    <SelectItem value="open_containers">Open Containers Only</SelectItem>
                    <SelectItem value="category">Category Specific</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label>Category Filter (optional)</Label>
                <Select
                  value={newCount.categoryFilter}
                  onValueChange={(v) => setNewCount({ ...newCount, categoryFilter: v })}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="All Categories" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="">All Categories</SelectItem>
                    <SelectItem value="Dairy">Dairy</SelectItem>
                    <SelectItem value="Flavoring">Flavoring</SelectItem>
                    <SelectItem value="Packaging">Packaging</SelectItem>
                    <SelectItem value="Allergens">Allergens</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="flex justify-end gap-2">
                <Button variant="outline" onClick={() => setShowCreateDialog(false)}>
                  Cancel
                </Button>
                <Button onClick={() => createMutation.mutate()} disabled={createMutation.isPending}>
                  Create Count
                </Button>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      <div className="grid grid-cols-4 gap-4">
        <Card>
          <CardContent className="pt-6">
            <div className="text-center">
              <p className="text-3xl font-bold text-red-600">
                {counts?.filter(c => isPast(new Date(c.scheduled_date)) && c.status === 'scheduled').length || 0}
              </p>
              <p className="text-sm text-muted-foreground">Overdue</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-center">
              <p className="text-3xl font-bold text-yellow-600">
                {counts?.filter(c => c.status === 'pending_review').length || 0}
              </p>
              <p className="text-sm text-muted-foreground">Pending Review</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-center">
              <p className="text-3xl font-bold text-blue-600">
                {counts?.filter(c => c.status === 'in_progress').length || 0}
              </p>
              <p className="text-sm text-muted-foreground">In Progress</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-center">
              <p className="text-3xl font-bold text-orange-600">
                {counts?.filter(c => isToday(new Date(c.scheduled_date)) && c.status === 'scheduled').length || 0}
              </p>
              <p className="text-sm text-muted-foreground">Due Today</p>
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="flex gap-4">
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-48">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="active">Active (Not Completed)</SelectItem>
            <SelectItem value="all">All Counts</SelectItem>
            <SelectItem value="scheduled">Scheduled</SelectItem>
            <SelectItem value="in_progress">In Progress</SelectItem>
            <SelectItem value="pending_review">Pending Review</SelectItem>
            <SelectItem value="approved">Approved</SelectItem>
          </SelectContent>
        </Select>
      </div>

      <Card>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Status</TableHead>
              <TableHead>Count #</TableHead>
              <TableHead>Type</TableHead>
              <TableHead>Scheduled</TableHead>
              <TableHead>Items</TableHead>
              <TableHead>Progress</TableHead>
              <TableHead>Variances</TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {counts?.map((count) => (
              <TableRow key={count.id}>
                <TableCell>{getStatusBadge(count)}</TableCell>
                <TableCell className="font-medium">{count.count_number}</TableCell>
                <TableCell className="capitalize">{count.count_type.replace('_', ' ')}</TableCell>
                <TableCell>{format(new Date(count.scheduled_date), 'MMM d, yyyy')}</TableCell>
                <TableCell>{count.total_items}</TableCell>
                <TableCell>
                  {count.items_counted}/{count.total_items}
                </TableCell>
                <TableCell>
                  {count.items_with_variance > 0 && (
                    <Badge variant="destructive">
                      {count.items_with_variance}
                    </Badge>
                  )}
                </TableCell>
                <TableCell>
                  {count.status === 'scheduled' && (
                    <Button size="sm" onClick={() => navigate(`/warehouse/cycle-counts/${count.id}`)}>
                      Start
                    </Button>
                  )}
                  {count.status === 'in_progress' && (
                    <Button size="sm" onClick={() => navigate(`/warehouse/cycle-counts/${count.id}`)}>
                      Continue
                    </Button>
                  )}
                  {count.status === 'pending_review' && (
                    <Button size="sm" onClick={() => navigate(`/warehouse/cycle-counts/${count.id}/review`)}>
                      Review
                    </Button>
                  )}
                  {count.status === 'approved' && (
                    <Button size="sm" variant="outline" onClick={() => navigate(`/warehouse/cycle-counts/${count.id}`)}>
                      View
                    </Button>
                  )}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Card>
    </div>
  );
};

export default CycleCounts;
